// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIj2OIM1IxmBIIBmqUKeNRao3jQPob3w',
    appId: '1:828766284373:android:e8a67212a7c54eb0b082dc',
    messagingSenderId: '828766284373',
    projectId: 'hanaang',
    storageBucket: 'hanaang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthRcSQrZTNJbznJGui5CxGSR35EpKqfQ',
    appId: '1:828766284373:ios:cb2f8ca4192c2b4eb082dc',
    messagingSenderId: '828766284373',
    projectId: 'hanaang',
    storageBucket: 'hanaang.appspot.com',
    androidClientId: '828766284373-2h0qkm0ttsbkrb4ebduo9e0f8u699b1e.apps.googleusercontent.com',
    iosClientId: '828766284373-1drg8pv29pgmloedhpsd1vhijcn70f7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminHanaang',
  );
}
